//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭМК.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachment
    {
        public int id_attachment { get; set; }
        public int id_hospital { get; set; }
        public int id_patient { get; set; }
    
        public virtual hospital hospital { get; set; }
        public virtual patient patient { get; set; }
    }
}
