//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭМК.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class history_the_disease
    {
        public int id_history { get; set; }
        public int id_patient { get; set; }
        public int id_doctor { get; set; }
        public string place_of_education { get; set; }
        public System.DateTime periody_hospitalization { get; set; }
        public System.DateTime clinic_diagnosis { get; set; }
        public System.DateTime results_examinationn { get; set; }
        public System.DateTime recommendations { get; set; }
    }
}
