//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭМК.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inspection()
        {
            this.disability_certificate = new HashSet<disability_certificate>();
            this.prescription_form_107у = new HashSet<prescription_form_107у>();
            this.referral = new HashSet<referral>();
        }
    
        public int id_inspection { get; set; }
        public int id_patient { get; set; }
        public int id_doctor { get; set; }
        public System.DateTime date_inspection { get; set; }
        public System.TimeSpan time_inspection { get; set; }
        public string place_of_service { get; set; }
        public string type_of_service_case { get; set; }
        public string type_of_payment { get; set; }
        public string purpose_of_the_service { get; set; }
        public string complaints { get; set; }
        public string medical_history { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> blood_pressure_upper { get; set; }
        public Nullable<int> blood_pressure_lower { get; set; }
        public Nullable<double> temperature { get; set; }
        public Nullable<int> heart_rate { get; set; }
        public Nullable<int> respiratory_rate { get; set; }
        public Nullable<int> oxygen_saturation { get; set; }
        public string preliminary_diagnosis { get; set; }
        public string the_main_diagnosis { get; set; }
        public string patient_condition { get; set; }
        public string suspicion_of_heat { get; set; }
        public string treatment { get; set; }
        public string recommendations { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disability_certificate> disability_certificate { get; set; }
        public virtual doctor doctor { get; set; }
        public virtual patient patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prescription_form_107у> prescription_form_107у { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<referral> referral { get; set; }
    }
}
