//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭМК.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class diplomEntities : DbContext
    {
        public diplomEntities()
            : base("name=diplomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attachment> attachment { get; set; }
        public virtual DbSet<doctor> doctor { get; set; }
        public virtual DbSet<history_the_disease> history_the_disease { get; set; }
        public virtual DbSet<hospital> hospital { get; set; }
        public virtual DbSet<inspection> inspection { get; set; }
        public virtual DbSet<medical_care_profile> medical_care_profile { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<representative_patient> representative_patient { get; set; }
        public virtual DbSet<specialization> specialization { get; set; }
        public virtual DbSet<surveillance_journal> surveillance_journal { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
