//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭМК.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedCardDBEntities : DbContext
    {
        public MedCardDBEntities()
            : base("name=MedCardDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attachment> attachment { get; set; }
        public virtual DbSet<disability_certificate> disability_certificate { get; set; }
        public virtual DbSet<doctor> doctor { get; set; }
        public virtual DbSet<hospital> hospital { get; set; }
        public virtual DbSet<inspection> inspection { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<period> period { get; set; }
        public virtual DbSet<prescription_form_107у> prescription_form_107у { get; set; }
        public virtual DbSet<referral> referral { get; set; }
        public virtual DbSet<representative_patient> representative_patient { get; set; }
        public virtual DbSet<specialization> specialization { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
