//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭМК.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.attachment = new HashSet<attachment>();
            this.inspection = new HashSet<inspection>();
            this.representative_patient = new HashSet<representative_patient>();
        }
    
        public int id_patient { get; set; }
        public string snils { get; set; }
        public string lastname { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public System.DateTime birthday { get; set; }
        public byte age { get; set; }
        public string gender { get; set; }
        public string name_insurance_company { get; set; }
        public string number_policy_OMS { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attachment> attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inspection> inspection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<representative_patient> representative_patient { get; set; }
    }
}
