//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭМК.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class period
    {
        public int id_period { get; set; }
        public int id_disability_certificate { get; set; }
        public System.DateTime date_start { get; set; }
        public System.DateTime date_end { get; set; }
    
        public virtual disability_certificate disability_certificate { get; set; }
    }
}
