//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭМК.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescription_form_107у
    {
        public int number { get; set; }
        public int id_inspection { get; set; }
        public System.DateTime date { get; set; }
        public string name_of_the_drug { get; set; }
        public string dosage { get; set; }
        public string method_of_administration { get; set; }
        public string method_of_administration_details { get; set; }
        public string dosage_regimen { get; set; }
        public string dosage_regimen_optional { get; set; }
        public string duration_of_treatment_number { get; set; }
        public string duration_of_treatment_duration { get; set; }
        public string duration_of_treatment_comments { get; set; }
        public string justification_of_appointment { get; set; }
    
        public virtual inspection inspection { get; set; }
    }
}
