//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭМК.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class referral
    {
        public int id_referral { get; set; }
        public int id_inspection { get; set; }
        public string type_of_direction { get; set; }
        public Nullable<System.DateTime> date_of_creation { get; set; }
        public string payment_source { get; set; }
        public string service { get; set; }
        public string organization { get; set; }
        public string doctor { get; set; }
        public Nullable<System.DateTime> date_of_admission { get; set; }
        public string justification { get; set; }
    
        public virtual inspection inspection { get; set; }
    }
}
