//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭМК.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class representative_patient
    {
        public int number_representative { get; set; }
        public string name_representative { get; set; }
        public string lastname { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public System.DateTime document { get; set; }
        public string series { get; set; }
        public int number { get; set; }
        public string issued_by_whom { get; set; }
        public string release_datet_the_document { get; set; }
        public string phone { get; set; }
        public int id_patient { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
