//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ЭМК.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class surveillance_journal
    {
        public int record_number { get; set; }
        public int date_recording { get; set; }
        public int history_number { get; set; }
        public string temperature { get; set; }
        public System.DateTime complaints { get; set; }
        public System.DateTime general_condition_the_patient { get; set; }
    }
}
